app/views.py
from flask import Blueprint, render_template, request, redirect, url_for
from .models import * 

views = Blueprint('views',__name__)

@views.route("/")
def index():    
    return render_template("index.html")

@views.route("/inscription", methods=['GET','POST'])
def inscription():
    if request.method=='POST':
        nom = request.form['nom']
        prenom = request.form['prenom']
        datenaissance = request.form['datenaissance']
        niveau = request.form['niveau']
        add(nom, prenom, datenaissance, niveau)
        return redirect(url_for('views.formation'))

    return render_template("inscription.html")

@views.route("/seance", methods=['GET','POST'])
def seance():
    if request.method == "POST":
        num = int(request.form.get('groupe-loop'))
        first_index = int(request.form.get('first-etudiant-index'))
        seance = int(request.form.get('num-seance'))
        today = get_today_reg()
        etudiant_status = []
        for i in range(0+first_index,num+first_index):
            name = request.form.get(f'etudiant-name-{i}')
            present = int(request.form.get(f'etudiant-present-{i}'))
            payer = int(request.form.get(f'payer-etudiant-{i}'))
            etudiant_status.append([name,seance,present,payer])
            assister(name,present,seance,today)
            gestion_presence(name,seance,payer)

    seances = generate_seance()
    formations = [formation_de_groupe(seance[1]) for seance in seances]
    etudiants = [etudiants_de_groupe(seance[1]) for seance in seances]
    soldes = []
    m = []
    i = 0
    k = 0
    for etudiant in etudiants:
        f = formations[i]
        soldes.append([solde_de_etudiant(e,f) for e in etudiant])
        m.append([i for i in range(1+k,len(etudiant)+1+k)])
        i += 1
        k += len(etudiant)
    return render_template("seance.html", data = zip(seances, formations, etudiants, soldes, m))

@views.route("/formation", methods=['GET','POST'])
def formation():        
    if request.method=="POST":
        formation = request.form.get('formation')
        is_test = (request.form.get('test') == 'true')
        name = request.form.get('etudiant_name').split(' ')
        inscription_complet(formation,name[1],name[0],is_test)

    etudiants = list(generate_etudiants())
    niveaux = list(generate_niveau())
    autre_formations = list(generate_autre_formations())
    formations_etudiants = [list(generate_formations(etudiant[1], etudiant[0])) for etudiant in etudiants]
    formations_chaque_etudiant = []
    for formation in formations_etudiants:
        if formation == autre_formations:
            formations_chaque_etudiant.append(formation)
        else:
            formations_chaque_etudiant.append(formation+autre_formations)
    
    return render_template("formation.html", data=zip(etudiants,formations_chaque_etudiant,niveaux))

@views.route("/groupe", methods=['GET','POST'])
def groupe():
    if request.method == "POST":
        choice = request.form.get('seance').split(' ')
        jour = choice[0]
        heur = choice[1]
        code_groupe = request.form.get('groupe_code')
        affecter_a_seance(code_groupe,jour,heur)

    groupes, formations = generate_full_groupes()
    seances_chaque_groupe = [seance_disponible(groupe[0]) for groupe in groupes]
    return render_template("groupe.html", data = zip(groupes, formations, seances_chaque_groupe))

@views.route("/etudiant")
def etudiant():
    etudiants,formation_groupe = generate_info_etudiants()
    return render_template("etudiant.html", data = zip(etudiants,formation_groupe))

@views.route("/home")
def home():
    return render_template("home.html")

app/templates/admin.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Admin</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap" rel="stylesheet">
</head>

<body>
    <main>
        <h1>admin Login Page</h1>
        <form method="POST" id="ad-login">
            <label for="username">Username:</label>
            <input class="input-text" type="text" id="username" name="username" placeholder="Enter username">
            <label for="Password">Password:</label>
            <input class="input-text" type="password" id="Password" name="Password" placeholder="Enter password">
            <button type="submit" >
                Login
            </button>
            {% with messages = get_flashed_messages(with_categories=true) %} 
            {% if messages %}
            {% for category, message in messages %}
            {% if category == 'error' %}
            <div class="alert alert-danger alter-dismissable fade show" role="alert">
                <p>{{ message }}</p>
            </div>
            {% endif %}
            {% endfor %}
            {% endif %}
            {% endwith %}
        </form>
    </main>

</body>

</html>

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}base{% endblock %}</title>
    <link
      rel="stylesheet"
      href="{{ url_for('static', filename='style.css') }}"
    />
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap"
      rel="stylesheet"
    />
  </head>
  <body>
    <header>
      <nav class="navbar">
        <div class="navdiv">
          <ul>
            <li><a href="{{ url_for('views.inscription') }}">Inscription</a></li>
            <li><a href="{{ url_for('views.formation') }}">Formation</a></li>
            <li><a href="{{ url_for('views.groupe') }}">Groupe</a></li>
            <li><a href="{{ url_for('views.seance') }}">Seance</a></li>
            <li><a href="{{ url_for('views.etudiant') }}">Etudiant</a></li>
            <li><a href="{{ url_for('views.home') }}">home</a></li>
          </ul>
        </div>
      </nav> 
    </header>

    <main>
      {% block content %} {% endblock %}
    </main>

  </body>
  <script src="{{ url_for('static', filename='script.js') }}"></script>
</html>

app/templates/etudiant.html
{% extends "base.html" %} {% block title %}Enseignant{% endblock %}
{% block content %}

<div class="etudiant-form-list">
    <h2>Liste Des Etudiants</h2>
    <ul class="etudiant-list-items">
        {% for etudiant,formation_groupes in data%}{% set j=loop.index %}
        <li>
            <p class="etudiant-item-li" id="etudiant-{{j}}">
                {{ etudiant[0] }} {{ etudiant[1] }}
            </p>
            <p class="etudiant-item-li" id="etudiant-{{j}}">
              {{ etudiant[2] }}
          </p>
            <div class="popup" id="popup-about-{{j}}">
                <div class="overlay"></div>
                <div class="content">
                  <div class="close-btn" onclick="togglePopupAbout({{j}})">&times;</div>
                  <div class="formation-selection-etudiant">
                    <div class="etudiant-info-list">
                      <ul>
                        {% for formation_grp in formation_groupes %}
                        <li>
                          <div  class="etudiant-item-li">
                            <p class="etudiant-item-li">
                              {{ formation_grp[0] }}
                            </p>
                            <p class="etudiant-item-li">
                              Groupe {{ formation_grp[1] }}
                            </p>
                          </div>
                        </li>
                        {% endfor %}
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
              <button
                onclick="togglePopupAbout({{j}})"
                type="button"
                class="edit-btn-item"
              >
                about
              </button>
        </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

app/templates/formation.html
{% extends "base.html" %} {% block title %}Etudiant{% endblock %} {% block
content %}

<div class="etudiant-form-list">
  <h2>A Affecter</h2>
  <ul class="etudiant-list-items">
    {% for etudiant,formations,niveau in data %} {% set j = loop.index %}
    <li>
      <p class="etudiant-item-li" id="etudiant-line-{{loop.index}}">
        {{ etudiant[0] }} {{ etudiant[1] }}
      </p>
      <p class="etudiant-item-li">{{ niveau[0] }}</p>
      <div class="popup" id="popup-{{j}}">
        <div class="overlay"></div>
        <div class="content">
          <div class="close-btn" onclick="togglePopup({{j}})">&times;</div>
          <div class="formation-selection-etudiant">
            <form class="innerform" method="POST" name="innerform" id="innerform-etudiant-{{j}}">
              <select name="formation" id="formation-{{j}}">
                {% for formation in formations %}
                <option value="{{formation[0]}}">{{formation[0]}}</option>
                {% endfor %}
              </select>

              <div class="checkbox-selection">
                <input
                  type="checkbox"
                  id="test-check"
                  name="test"
                  value="true"
                />
                <label for="test" class="test-check">Test?</label><br />
              </div>
              <input
                type="hidden"
                name="etudiant_name"
                value="{{etudiant[0]}} {{etudiant[1]}}"
              />
              <button
                type="submit"
                class="edit-btn-item"
                id="add-line-{{j}}"
                onclick="toggleChoice()"
              >
                Ajouter
              </button>
            </form>
          </div>
          <hr />
          <p>A payer: <span id="argent-etudiant-{{j}}">0</span> DH</p>
        </div>
      </div>

      <button
        onclick="togglePopup({{j}})"
        type="button"
        class="edit-btn-item"
        id="edit-line-{{j}}"
      >
        edit
      </button>
    </li>
    {% endfor %}
  </ul>
</div>

{% endblock %}

app/templates/groupe.html
{% extends "base.html" %} {% block title %}Groupe{% endblock %}
{% block content %}

<div class="etudiant-form-list">
    <h2>Liste Des Groupes</h2>
    <ul class="etudiant-list-items">
        {% for groupe, formation, seances in data%}{% set j=loop.index %}
        <li>
            <p class="etudiant-item-li" id="groupe{{j}}">
                Groupe {{ groupe[0] }}
            </p>
            <p class="etudiant-item-li">{{ formation[0] }}</p>
            <p class="etudiant-item-li">{{ formation[1] }}</p>
            <div class="popup" id="groupe-about-{{j}}">
                <div class="overlay"></div>
                <div class="content">
                  <div class="close-btn" onclick="toggleGroupe({{j}})">&times;</div>
                  <div class="formation-selection-etudiant">
                    <form class="innerform" method="POST" name="innerformgroupe" id="innerform-group-{{j}}">

                      <select name="seance" id="seance{{j}}">
                        {% for seance in seances %}
                          <option value="{{seance[0][0]}} {{seance[1][0]}}">{{seance[0][0]}} {{seance[1][0]}}</option>
                        {% endfor %}
                      </select>

                      <input
                        type="hidden"
                        name="groupe_code"
                        value="{{groupe[0]}}"
                      />

                      <button
                        type="submit"
                        class="edit-btn-item"
                        id="add-seance-{{j}}"
                        onclick="activeEdit({{j}})"
                      >
                        Ajouter
                      </button>
                    </form>
                  </div>
                </div>
              </div>
        
              <button
                onclick="toggleGroupe({{j}})"
                type="button"
                class="edit-btn-item"
                id="edit-groupe-{{j}}"
              >edit</button>
        </li>
        {% endfor %}
    </ul>
</div>

{% endblock %}

app/templates/home.html
{% extends "base.html" %} {% block title %}Enseignant{% endblock %}
{% block content %}
<p>home</p>
{% endblock %}

app/templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>GSF</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@500&display=swap" rel="stylesheet">
</head>

<body>

    <main>
        <div>
            <h1>Gestion de Centre de Formation</h1>
            <div class="forms">
                <form action="/admin" method="get" id="admin">
                    <button type="submit">
                        Admin
                    </button>
                </form>
            </div>
        </div>

    </main>

</body>

</html>

app/templates/inscription.html
{% extends "base.html" %} 
{% block title %}Inscription{% endblock %}
{% block content %}

<h1>Nouveau Etudiant</h1>
<form method="post" id="inscription-form">
  <label for="prenom">Prenom:</label>
  <input
    class="input-text"
    type="text"
    id="prenom"
    name="prenom"
    placeholder="Enter prenom"
  />
  <label for="nom">Nom:</label>
  <input
    class="input-text"
    type="text"
    id="nom"
    name="nom"
    placeholder="Enter nom"
  />
  <label for="datenaissance">Date de Naissance:</label>
  <input
    class="input-date"
    type="date"
    id="datenaissance"
    name="datenaissance"
    placeholder="Enter nom"
  />
  <label for="niveau">Niveau:</label>
  <select class="select-niveau" name="niveau" id="niveau">
    <option value="2Bac">2Bac</option>
    <option value="1Bac">1Bac</option>
    <option value="TC">TC</option>
    <option value="3Col">3Col</option>
    <option value="autre">autre</option>
  </select>
  <button type="submit">Ajouter</button>
</form>

{% endblock %}

app/templates/seance.html
{% extends "base.html" %} {% block title %}Seance{% endblock %} {% block content
%}

<div class="etudiant-form-list">
  <h2>Liste Des Seances</h2>
  <ul class="etudiant-list-items">
    {% for seance, formation, etudiants, soldes, m in data%}{% set j =
    loop.index %}
    <li>
      <p class="etudiant-item-li" id="groupe{{j}}">Seance {{ seance[0] }}</p>
      <p class="etudiant-item-li">Groupe {{ seance[1] }}</p>
      <p class="etudiant-item-li">{{ formation }}</p>
      <div class="popup-seance" id="seance-about-{{j}}">
        <div class="overlay"></div>
        <div class="content-seance">
          <div class="close-btn" onclick="toggleSeance({{j}})">&times;</div>
          <div class="formation-selection-seance">
            <form
              class="form-seance"
              method="POST"
              name="form-seance"
              id="form-seance-{{j}}"
            >
              {% for etudiant in etudiants %} {% set i = loop.index0 %} {% set
              solde = soldes[i][0] %}{% set m_id = m[i] %}
              <div
                class="innerformseance"
                name="innerformseance"
                id="innerform-seance-{{m_id}}"
              >
                <p class="etudiant-item-li">
                  {{ etudiant[1] }} {{ etudiant[0] }}
                </p>
                <p class="etudiant-item-li" id="solde-etudiant-{{m_id}}">
                  {{ solde }}
                </p>
                
                <input
                  type="hidden"
                  name="etudiant-name-{{m_id}}"
                  value="{{ etudiant[1] }} {{etudiant[0]}}"
                />
                <input type="hidden" name="num-seance" value="{{j}}" />
                <input type="hidden" name="first-etudiant-index" value="{{ m_id }}"/>
                <input
                  type="hidden"
                  name="groupe-loop"
                  value="{{loop.length}}"
                />
                <input
                  type="hidden"
                  name="etudiant-present-{{m_id}}"
                  id="etudiant-present-{{m_id}}"
                  value="0"
                />
                <input type="hidden" name="payer-etudiant-{{m_id}}" id="payer-etudiant-{{m_id}}" value="0" />
                <button
                  type="button"
                  class="present-btn-item"
                  id="present-seance-{{m_id}}"
                  onclick="toggleAbsent({{m_id}})"
                >
                  Present
                </button>

                <button
                  type="button"
                  class="payer-btn-item"
                  id="payer-seance-{{m_id}}"
                  onclick="togglePayer({{m_id}})"
                  disabled
                >
                  Payer
                </button>
              </div>
              {% endfor %}
              <button type="submit" class="edit-btn-item" id="save-btn-{{j}}">
                Save
              </button>
            </form>
          </div>
        </div>
      </div>

      <button
        onclick="toggleSeance({{j}})"
        type="button"
        class="edit-btn-item"
        id="edit-seance-{{j}}"
      >
        controler
      </button>
    </li>
    {% endfor %}
  </ul>
</div>

{% endblock %}